import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const linkClass = 'block p-4 text-center hover:underline';

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <div className='fixed h-full w-48 m-0 p-0 bg-red-600 border-2 border-black overflow-auto'>
          <Link href='/' className={linkClass}>Home</Link>
          <Link href='/scales' className={linkClass}>Scales</Link>
          <Link href='/options' className={linkClass}>Options</Link>
          <Link href='/account' className={linkClass}>Account</Link>
        </div>
        <div className={inter.className + 'fixed ml-48'}>{children}</div>
      </body>
    </html>
  )
}
